configs:
  params: 
    server.insecure: true
  cm:
    # Reference: https://docs.crossplane.io/v1.10/guides/argo-cd-crossplane/#configuring-argo-cd-with-crossplane
    application.resourceTrackingMethod: annotations

    timeout.reconciliation: 30s
    url: https://argocd.<YOUR_DOMAIN>

    ## If Google SSO
    # dex.config: |
    #   connectors:
    #   - config:
    #       redirectURI: https://argocd.<YOUR_DOMAIN>/api/dex/callback
    #       clientID: #### YOUR CLIENT ID ####
    #       clientSecret: #### YOUR CLIENT SECRET ####
    #       serviceAccountFilePath: /tmp/oidc/googleAuth.json
    #       adminEmail: #### ADMIN EMAIL ####
    #       hostedDomains: 
    #         - <YOUR_DOMAIN>
    #     type: google
    #     id: google
    #     name: Google
  
  rbac: 
    policy.default: role:readonly
    # policy.csv: |
    #   g, <YOUR_GOOGLE_DEVOPS_GROUP>@<YOUR_DOMAIN>.com, role:admin

repoServer: 
  autoscaling: 
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

server:
  autoscaling: 
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  service:
    type: ClusterIP

  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts: 
      - argocd.<YOUR_DOMAIN>
    paths:
      - "/"
    pathType: Prefix
    tls: 
      - secretName: argocd-server-tls
        hosts:
          - argocd.<YOUR_DOMAIN>

## If Google SSO
# dex:
#   volumes:
#   - name: google-json
#     secret:
#       defaultMode: 420
#       secretName: argocd-google-groups-json
#   volumeMounts:
#   - mountPath: /tmp/oidc
#     name: google-json
#     readOnly: true